### ISSUE TITLE
Change the way fragment.manual is evaluated

### ISSUE THREAD

**Issue by bloodyowl** [DanielRapp/fragment.js#10]
As at [line 3]([https://github.com/DanielRapp/fragment.js/blob/master/fragment.js#L3) , a local `fragment` variable is defined, if you want to make [line 139](https://github.com/DanielRapp/fragment.js/blob/master/fragment.js#L139) efficient, you would better use 

``` javascript
if (!window.fragment.manual)
```

instead of 

``` javascript
if (!fragment.manual)
```

or save a local variable of the actual `window.fragment` in the first place.

**Comment by DanielRapp** [comment]
[Fixed](https://github.com/DanielRapp/fragment.js/commit/7e6a32e33ff8a1ae5b347ca964dc352728cfe6b0). Though the API to control the manual toggle is still really awkward.
