### ISSUE TITLE
Error fetching package from Bower

### ISSUE THREAD

**Issue by rudeayelo** [DanielRapp/fragment.js#16]
Just FYI, I think the package registry in Bower is wrong, you have:

`fragment git://github.com:DanielRapp/fragment.js`

I registered it again as fragment.js with this URL:

`fragment.js git://github.com/DanielRapp/fragment.js.git`

**Comment by DanielRapp** [comment]
Strange, I thought I tried it. But you're right, it doesn't work. Thanks!
