### ISSUE TITLE
JSONP support

### ISSUE THREAD

**Issue by DanielRapp** [DanielRapp/fragment.js#2]
JSONP support should be added, but I can't think of an elegant API implementation. I originally just wanted to detect if the `data-fragment-json` url contained `callback`, but that leaves out APIs, like [reddit](http://www.reddit.com/.json?limit=1&jsonp=example), that uses `jsonp` instead.

Adding a whole new attribute just for that feels unnecessary and inelegant.

**Comment by pudo** [comment]
+1, that would make the json+template thing a killer.

**Comment by DanielRapp** [comment]
Added! See the bottom of [the demo page](http://danielrapp.github.com/fragment.js/) for an example using the twitter API
