### ISSUE TITLE
Can not working for me !!

### ISSUE THREAD

**Issue by hfeeki** [DanielRapp/fragment.js#3]
It can not load fragment for me!

**Comment by DanielRapp** [comment]
Does the demo page work? What browser and OS are you on?

**Comment by hfeeki** [comment]
chrome and firefox , ubuntu linux 12

**Comment by DanielRapp** [comment]
And what version of both?

**Comment by hfeeki** [comment]
chrome: 23.0.1271.95 
firefox: 18.0.1

**Comment by DanielRapp** [comment]
It's working for me on Chrome for mac version 23.0.1271.101 (the only 23.0.1271.\* I could find), I'll try to get a Linux box started within a few days.
