### ISSUE TITLE
Support for nested templates

### ISSUE THREAD

**Issue by AYLIEN** [DanielRapp/fragment.js#6]
would be sweet:

layout.html:

``` html
<div data-fragment="partial1.html"></div>
<script src="fragment.js"></script>
```

partial1.html:

``` html
<div data-fragment="partial2.html"></div>
```

partial2.html:

``` html
<strong>you made it</strong>
```

and receive:

``` html
<div data-fragment="partial1.html">
  <div data-fragment="partial2.html">
    <strong>you made it</strong>
  </div>
</div>
```

at the end.

**Comment by mendeza** [comment]
+1
This was the second thing I tried, after rendering a single fragment. Then it would have more typical "include" behavior.

**Comment by DanielRapp** [comment]
Better late than never! This was added in the latest version.
