### ISSUE TITLE
Callback mechanism

### ISSUE THREAD

**Issue by AYLIEN** [DanielRapp/fragment.js#7]
a callback mechanism for once a fragment/all fragments are loaded seems necessary, as neither $(document).ready() nor $(element).ready() would work for obvious reasons.

**Comment by DanielRapp** [comment]
Yet another great idea. Thanks :)

**Comment by rudeayelo** [comment]
+1 to this!

**Comment by rabu81** [comment]
+1 for this one... this feature is really needed!

**Comment by sakamies** [comment]
+1! I was just wondering how to do this, didn't figure out a better way than using a timeout.

**Comment by DanielRapp** [comment]
Finally got around to implementing this.
Just add an event listener to the ready fragment.ready property, and it'll be called when all fragments have been loaded! (With the number of fragments loaded as the first and only parameter.) Like so:

``` javascript
fragment = {
  ready: function(num_fragments) {
    console.log(num_fragments + " fragments were loaded");
  }
};
```
