### ISSUE TITLE
Doesn't work for me, i am using Mustache.js in Chrome browser

### ISSUE THREAD

**Issue by mrudulachunduri** [DanielRapp/fragment.js#8]
i created a simple example using fragment.js and mustache.js. But the line of code 
var fragments = document.querySelectorAll('[data-'+fragment.json+']:not([data-'+fragment.html+'])');

doesn't give any fragments.

<div data-fragment-json="testFragment.json">
Testing fragment by {{ name }}
</div>

**Comment by mrudulachunduri** [comment]
can you upload any demo that you have

**Comment by ghost** [comment]
It works for me if I move the scripts before the closing "body".

I tested in Chrome 26.0.1410.43 and Firefox 19.0.2 and 20.0

**Comment by mrudulachunduri** [comment]
Hey thanks to let me know..... it worked for me too after moving it at the end of the body closing tag. I tested with Underscore.js and mustache.js and only mustache is working for me

**Comment by DanielRapp** [comment]
I just tested mustache.js and undescore.js and it seems to work. If both mustache and underscore are loaded, only mustache will be used to parse the string. If you could provide a simple, non-functioning, html sample for me to debug, that'd be great.

P.S. Trevligt att se ännu en Linköpingsbo här på Github :)
